env: local

http_server:
  address: "localhost:8081"

storage:
  type: postgres

  postgres:
    host: localhost
    port: 5432
    user: linkshelf
    password: linkshelf
    dbname: linkshelf
    sslmode: disable
